### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by HappySean2845** [Bonfida/solana-name-service-guide#1]
![image](https://user-images.githubusercontent.com/7857661/149061372-be09ed83-9bda-4151-b95f-cd4b0ee08c51.png)

**Comment by dr497** [comment]
Thanks.

Fixed here https://github.com/Bonfida/solana-name-service-guide/commit/8d186c69391219c3e7996fa638fb9913fe1044d1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
