### ISSUE TITLE
@bonfida_spl-name-service.js does not provide an export named 'SOL_TLD_AUTHORITY'

### ISSUE THREAD

**Issue by chongkan** [Bonfida/solana-name-service-guide#29]
![image](https://github.com/Bonfida/solana-name-service-guide/assets/4944252/43511eb6-0d16-49c2-8a78-38f2e8beed8c)

Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@bonfida_spl-name-service.js?v=08295449' does not provide an export named 'SOL_TLD_AUTHORITY'

https://sns.guide/domain-name/transfer.html

**Comment by akashrdev** [comment]
Thanks for flagging, we'll update this and confirm here once done.

**Comment by chongkan** [comment]
Update: it should be replaced by ROOT_DOMAIN_ACCOUNT (58PwtjSDuFHuUkYjH9BYnnQKHfwo9reZhC2zMJv9JPkx)

**Comment by dr497** [comment]
@chongkan Thanks a lot for opening the issue, you are correct, `SOL_TLD_AUTHORITY` was renamed `ROOT_DOMAIN_ACCOUNT` but we forgot to update certain parts of the documentation.

This commit 3ac7c27b65fcea8b413f78679aff136baca003c2 fixes it.
